<?php
/*SELECT PRODUKTY.NAZWA,SUM(ILOSC) FROM  MAGAZYN,ZAWARTOSC_MAGAZYNU,PRODUKTY
WHERE MAGAZYN.ID = ZAWARTOSC_MAGAZYNU.ID_MAGAZYNU AND ZAWARTOSC_MAGAZYNU.ID_PRODUKTU = PRODUKTY.ID AND MAGAZYN.ID= 1
GROUP BY  PRODUKTY.NAZWA
*/
require "../db_con.php";
        

$query = "SELECT PRODUKTY.NAZWA AS NAZWA,SUM(ILOSC) AS ILOSC FROM  MAGAZYN,ZAWARTOSC_MAGAZYNU,PRODUKTY
WHERE MAGAZYN.ID = ZAWARTOSC_MAGAZYNU.ID_MAGAZYNU AND ZAWARTOSC_MAGAZYNU.ID_PRODUKTU = PRODUKTY.ID AND MAGAZYN.ID= ".$_GET['id']."
GROUP BY  PRODUKTY.NAZWA";

foreach ($conn->query($query) as $row) {
    $arr[] = $row;
}
if(isset($arr)){
    echo json_encode($arr);
} else 
 echo "BRAK";
    


?>