
<?php 
   if($_GET['ID'])
        {
            $ID = $_GET['ID'];
            require "../db_con.php";
            
            //$sql  ="SELECT PRODUKTY.CEMA_BRUTTO,PRODUKTY.MARZA,PRODUKTY.ID AS ID,PRODUKTY.NAZWA AS NAZWA,PRODUKTY.OPIS AS OPIS,PRODUKTY.NA_RECEPTE AS RECEPTA,PRODUKTY.ZDJECIE AS ZDJECIE,PRODUCENT.NAZWA AS PRODUCENT_NAZWA,PRODUKTY.CENA_NETTO AS CENA_NETTO FROM PRODUKTY,PRODUCENT WHERE PRODUKTY.ID_PRODUCENT = PRODUCENT.ID AND PRODUKTY.ID = ".$ID."";
            $sql = "SELECT PRODUKTY.PROCENT_VAT,PRODUKTY.MARZA,PRODUKTY.CENA_BRUTTON,PRODUKTY.ID AS ID,PRODUKTY.NAZWA AS NAZWA,PRODUKTY.OPIS AS OPIS,PRODUKTY.NA_RECEPTE AS RECEPTA,PRODUKTY.ZDJECIE AS ZDJECIE,PRODUCENT.ID AS PRODUCENT_ID,PRODUKTY.CENA_NETTO AS CENA_NETTO, kategoria.id_pod_kategoria AS KAT_POD, kategoria.id_kategoria_glowna AS KAT_GL FROM PRODUKTY,PRODUCENT,KATEGORIA WHERE PRODUKTY.ID_PRODUCENT = PRODUCENT.ID AND PRODUKTY.ID_KATEGORIA = KATEGORIA.ID AND PRODUKTY.ID= ".$ID."";
            foreach ($conn->query($sql) as $row) {
                echo json_encode($row);
            }
            
        }
        else{
            echo json_encode("error");
        }


?>